services:
  info-orb-proxies:
    build: .
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - timezone_cache:/var/cache/timezone_proxy
      - ./mlb_logos:/app/mlb_logos
      - ./nlf_logos:/app/nfl_logos
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "2m"
        max-file: "5"    

volumes:
  timezone_cache:  # Auto-created if doesn't exist
