services:
  proxy:
    build: .
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - timezone_cache:/var/cache/timezone_proxy
      - ./mlb_logos:/app/mlb_logos
    restart: unless-stopped

volumes:
  timezone_cache:  # Auto-created if doesn't exist
