services:
  proxy:
    build: .
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - timezone_cache:/var/cache/timezone_proxy
    restart: unless-stopped

volumes:
  timezone_cache:  # Auto-created if doesn't exist
