services:
  - type: web
    name: your-web-app
    env: docker
    dockerfilePath: ./Dockerfile
    port: 80
    disk:
      name: timezone_cache
      mountPath: /opt/render/project/persistent
      sizeGB: 1

  - type: worker
    name: timezone-preloader
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    instanceType: free
    startCommand: python /app/scripts/preload_timezones.py
    disk:
      name: timezone_cache_worker
      mountPath: /opt/render/project/persistent_worker
      sizeGB: 1
