services:
  # Web service (original)
  - type: web
    name: your-web-app
    env: docker
    dockerfilePath: ./Dockerfile
    port: 80
    disk:
      name: timezone_cache # Primary disk for the web service
      mountPath: /opt/render/project/persistent
      sizeGB: 1

  # Background worker (updated)
  - type: worker
    name: timezone-preloader
    env: docker
    dockerfilePath: ./Dockerfile
    command: python /app/scripts/preload_timezones.py
    # Option 1: Use a separate disk (safer)
    disk:
      name: timezone_cache_worker # Unique name
      mountPath: /opt/render/project/persistent_worker
      sizeGB: 1
